(in-package :clint-tests)

(defsuite clint ())
(defsuite special-forms (clint))
(defsuite arithmetic (clint))
(defsuite appliers (clint))
(defsuite macros (clint))
(defsuite list (clint))
(defsuite setters (clint))

(deftest quote (special-forms)
  (assert-eql ^'x (eval-string "'x "))
  (assert-equal ^'(a b c) (eval-string "'(a b c)")))

(deftest if (special-forms)
  (assert-eql 2   (eval-string "(if 1 2 3)"))
  (assert-eql 3   (eval-string "(if '() 2 3)"))
  (assert-eql 2   (eval-string "(if 1 2)"))
  (assert-eql nil (eval-string "(if 1 '())")))

(deftest progn (special-forms)
  (assert-eql 1 (eval-string "(progn 1)"))
  (assert-eql 2 (eval-string "(progn 1 2)"))
  (assert-eql 3 (eval-string "(progn 1 2 3)")))

(deftest lambda (special-forms)
  (assert-eql 10 (eval-string "((lambda (x y) (+ x y)) 3 7)"))
  (assert-eql 20 (eval-string "((lambda (x) (* 4 x)) 5)"))
  (assert-equal '(30 110 60 115)
      (eval-string "(let* ((acc-gen (lambda (n) (lambda (x) (setf n (+ x n)))))
                           (a (funcall acc-gen 10))
                           (b (funcall acc-gen 100)))
                       (cons (funcall a 20)
                         (cons (funcall b 10)
                           (cons (funcall a 30)
                             (cons (funcall b 5)
                                '())))))")))

(deftest + (arithmetic)
  (assert-eql 5 (eval-string "(+ 2 3)"))
  (assert-eql 10 (eval-string "(+ 5 5)"))
  (assert-eql 15 (eval-string "(+ 1 2 3 4 5)")))

(deftest - (arithmetic)
  (assert-eql 10  (eval-string "(- 15 5)"))
  (assert-eql 0   (eval-string "(- 10 10)"))
  (assert-eql -5  (eval-string "(- 10 15)"))
  (assert-eql -13 (eval-string "(- 1 2 3 4 5)")))

(deftest * (arithmetic)
  (assert-eql 20 (eval-string "(* 5 4)"))
  (assert-eql 15 (eval-string "(* 3 5)"))
  (assert-eql 24 (eval-string "(* 1 2 3 4)")))

(deftest / (arithmetic)
  (assert-eql 5/4 (eval-string "(/ 5 4)"))
  (assert-eql 2   (eval-string "(/ 10 5)"))
  (assert-eql 1/2 (eval-string "(/ 6 4 3)")))

(deftest +-*/ (arithmetic)
  (assert-eql 15 (eval-string "(* 5 (+ 3 (/ 8 (- 2 6)) (+ 1 1)))")))

(deftest funcall (appliers)
  (assert-eql 8 (eval-string "(funcall (lambda (x y) (+ x y 5)) 1 2)"))
  (assert-eql 15 (eval-string "(funcall (lambda (x) (+ x 5)) 10)"))
  (assert-eql 15 (eval-string "(funcall #'+ 1 2 3 4 5)")))

(deftest apply (appliers)
  (assert-eql 8 (eval-string "(apply (lambda (x y) (+ x y 5)) '(1 2))"))
  (assert-eql 120 (eval-string "(apply (lambda (w x y z) (* w x y z))
                                       2 3 '(4 5))"))
  (assert-eql 15 (eval-string "(apply #'+ '(1 2 3 4 5))")))

(deftest eval (appliers)
  (assert-eql 8 (eval-string "(eval '(+ 3 5))"))
  (assert-eql 20 (eval-string "(eval '(+ (* 5 3) 5))")))

(deftest let (macros)
  (assert-eql 5 (eval-string "(let ((x 2) (y 3)) (+ x y))"))
  (assert-eql 10 (eval-string "(let ((x 15)) (- x 5))")))

(deftest cond (macros)
  (assert-eql 2 (eval-string "(cond (1 2) (3 4))"))
  (assert-eql 4 (eval-string "(cond ('() 2) (3 4))")))

(deftest car (list)
  (assert-eql 1 (eval-string "(let ((x (cons 1 (cons 2 '())))) (car x))"))
  (assert-eql '() (eval-string "(let ((x '())) (car x))"))
  (assert-eql ^'a (eval-string "(car '(a . b))")))

(deftest cdr (list)
  (assert-equal '(2) (eval-string "(let ((x (cons 1 (cons 2 '())))) (cdr x))"))
  (assert-eql '() (eval-string "(let ((x '())) (car x))"))
  (assert-eql ^'b (eval-string "(cdr '(a . b))")))

(deftest setq (setters)
  (assert-eql 5  (eval-string "(let ((x 10)) (setq x 5) x)"))
  (assert-eql 10 (eval-string "(let ((y 15)) (setq y 10) y)")))

(deftest setf (setters)
  (assert-equal 5 (eval-string "(let ((x 10)) (setf x 5) x)"))
  (assert-equal '(1 10) (eval-string "(let ((x 10)) (setf x '(1 10)))")))

(deftest setf-car (setters)
  (assert-equal '(10 2 3) (eval-string "(let ((x (cons 1 (cons 2 (cons 3 '()))))) (setf (car x) 10) x)"))
  (assert-equal '(1 10 3) (eval-string "(let ((x (cons 1 (cons 2 (cons 3 '()))))) (setf (car (cdr x)) 10) x)")))

(deftest setf-cdr (setters)
  (assert-equal '(1 4 5) (eval-string "(let ((x (cons 1 (cons 2 (cons 3 '()))))) (setf (cdr x) '(4 5)) x)"))
  (assert-equal '((2 10) 4 5) (eval-string "(let ((x (cons (cons 2 (cons 10 '())) (cons 4 (cons 5 '())))))
                                              (setf (cdr (car x)) '(10)) x)")))
